CodeGen/nuttx/.gitignore, CodeGen/nuttx/README, CodeGen/nuttx/devices/Makefile, CodeGen/nuttx/devices/input.c, CodeGen/nuttx/devices/linear.c, CodeGen/nuttx/devices/matop.c, CodeGen/nuttx/devices/toNull.c, CodeGen/nuttx/include/matop.h, CodeGen/nuttx/include/pyblock.h, CodeGen/templates/nuttx.tmf
The model with PulseGenerator, Gain and NULL blocks
can be build and load as ELF file into running NuttX
system.
To build model, nuttx-export archive has to be extracted
and renamed to CodeGen/nuttx/nuttx-export .
NuttX project:
https://github.com/apache/incubator-nuttx
This pull request is intended mostly for review, discussion
and probably needs more work to be usable.
=> RFC: targets: added really basic skeleton for NuttX target.

CodeGen/nuttx/README, CodeGen/templates/nuttx.tmf
There are more options how to load and start model.
1) load model_name.elf into generic NuttX system with exported
symbols and start it as regular program
2) modify application entry point in NuttX configuration by change
CONFIG_USER_ENTRYPOINT="nsh_main"
to
CONFIG_USER_ENTRYPOINT="main"
Then compiled and linked system image starts directly linked in model.
3) left entry-point intact and register model as built-in
command into NuttX shell (NSH)
The provided changes implements the registration of the model main()
function as built-in executable "main", which can be started from
NuttX shell by simple typing "main".
Signed-off-by: Pavel Pisa <ppisa@pikron.com>
=> targets: NuttX - register model main() entry point as built-in command.

pysimCoder
When pysimCoder is run from GIT without running
python3 setup.py build
sudo python3 setup.py install
in pysimCoder/toolbox/supsictrl and pysimCoder/toolbox/supsisim
then required libraries cannot be found. Inform user that
such problem can be reslved by running with -s option
which setups required links in
$HOME/Documents/pysupsictrl/toolbox
and adjusts PYTHONPATH.
=> Update pysimCoder launch script to other users accounts and setup links.

Makefile
Doesn't work with a comma for me (GNU Make 4.3)
=> Fix dependency list in Makefile

CodeGen/nuttx/devices/Makefile, CodeGen/nuttx/devices/canopen.c
This commit introduces SocketCAN support for NuttX. New functions `socketCAN_open(char * dev)` and `socketCAN_saveMsg(struct can_frame m)` were added to support different open proccess and different NuttX structure of message, the overall princip remains the same (functions `canOpenTH(char * dev)` and `sendMsg(uint16_t ID, uint8_t DATA[], int len)` are called from block´s source code). File `canopen.c` now can support both characteristic device dev/can0 and socketcan.
There are also few unused functions like `rcvMsg(uint8_t DATA[], int timeout)`, `rcvMsgCob(int cob, uint8_t DATA[], int timeout)` and `canOpen(char * dev)`. I am not sure whether they should be removed as they do not support real time receive or whether they can have some usage.
SocketCAN communication was tested on existing …
=> NuttX: Added support for SocketCAN

CodeGen/templates/nuttx.tmf
Recent change to NuttX in commit [Make: use gcc as LD](https://github.com/apache/incubator-nuttx/commit/45672c269db13f59bdaa417e564837e8bbb6c8c1) changed usage of GCC. This commit fixes compile error in pysimCoder caused by this change and also supports previous NuttX versions. Tested with both current and older NuttX.
=> CodeGen/templates: updated nuttx.tmf to respect linking by both GCC and plane LD

CodeGen/nuttx/devices/nuttx_PWM.c, resources/blocks/blocks/NuttX/nuttx_PWM.xblk, resources/blocks/rcpBlk/NuttX/nuttx_PWMBlk.py, resources/blocks/rcpBlk/help/nuttx_PWMBlk.hlp
Updates PWM block for NuttX to support multiple channel PWM. Tested with Teensy 4.1 board with iMXRT MCU and NuttX.
=> NuttX: Updated PWM block to support multiple channels

CodeGen/Common/common_dev/switch_output.c, resources/blocks/Icons/SWITCH_OUT.svg, resources/blocks/blocks/nonlin/SwitchOut.xblk, resources/blocks/rcpBlk/help/switchOutBlk.hlp, resources/blocks/rcpBlk/nonlin/switchOutBlk.py
Added switch block that routes the input to one of the two outputs based on the compare value. Zero value is written to the output that is not currently used.
=> Common: Added switch block for two outputs

CodeGen/nuttx/devices/nuttx_Adc.c, CodeGen/nuttx/devices/nuttx_DAC.c, CodeGen/nuttx/devices/nuttx_PWM.c, resources/blocks/rcpBlk/NuttX/nuttx_AdcBlk.py, resources/blocks/rcpBlk/NuttX/nuttx_DACBlk.py, resources/blocks/rcpBlk/NuttX/nuttx_PWMBlk.py
Global static variables (mostly file descriptors and structures) were causing problems when multiple blocks of the same driver were used. This change should fix all of those global variables in NuttX subfolder. Integer parameter or pointer parameter was used to get file descriptors and structures to the functions based on some drivers without those problems (ENC or GPIO).
=> NuttX: Fixed problems when using multiple same blocks

CodeGen/Common/common_dev/discretePID.c, CodeGen/nuttx/devices/Makefile, CodeGen/nuttx/devices/TCPsocketTx.c, resources/blocks/Icons/PID.svg, resources/blocks/Icons/TCPSOCKET.svg, resources/blocks/blocks/Communication/TCPsocketTX.xblk, resources/blocks/blocks/linear/DiscretePID.xblk, resources/blocks/rcpBlk/Communication/TCPsocketTxBlk.py, resources/blocks/rcpBlk/help/TCPsocketTxBlk.hlp, resources/blocks/rcpBlk/help/discretePIDBlk.hlp, resources/blocks/rcpBlk/linear/discretePIDBlk.py
This PR adds discrete PID block with implemented anti-windup and TCP Socket TX block with added support for NuttX targets. The TCP communication was tested with tcpRTScope.py application (variation of serRTScope.py in BlockEditor/), which can be found here (https://github.com/michallenc/pysimCoder/blob/dc_motor/BlockEditor/tcpRTScope.py). It is currently just a working version without proper QT window (it still has options from serial application), but the data receive works.
=> Added discrete PID block and TCP Socket TX block

CodeGen/Common/common_dev/nonlinear.c
Cast from double to int type was causing problems with the precision of the block, resulting in returning true (false) even in some occasions when it should return false (true).
=> Common: fixed error in relation operation block

CodeGen/nuttx/.gitignore, CodeGen/nuttx/devices/nuttx_PWM.c
This PR removes global declaration of pwm_info_s structure and moves it locally to functions init() and inout() to support multiple PWM blocks. It is necessary to run for loop from 0 to CONFIG_PWM_NCHANNELS and set all channels to 0 also in inout() function, otherwise there will be hard faults. Also adds some comments as the code was getting a little bit harder to read.
I also experimented a little bit with completely removing pwm_info_s structure from init() function and then removing PWMIOC_SETCHARACTERISTICS ioctl command from that function too so init() would only open the device and then execute PWMIOC_START start command. It seemed to be working fine but then I found out that PWMIOC_SETCHARACTERISTICS should be sent before PWMIOC_START according to this …
=> Update nuttx_PWM.c file to support multiple PWM blocks

CodeGen/Common/common_dev/clarke_trans.c, CodeGen/Common/common_dev/park_trans.c, resources/blocks/Icons/FORWARD_CLARKE.svg, resources/blocks/Icons/FORWARD_PARK.svg, resources/blocks/Icons/INVERSE_CLARKE.svg, resources/blocks/Icons/INVERSE_PARK.svg, resources/blocks/blocks/Math/clarke_forward.xblk, resources/blocks/blocks/Math/clarke_inverse.xblk, resources/blocks/blocks/Math/park_forward.xblk, resources/blocks/blocks/Math/park_inverse.xblk, resources/blocks/rcpBlk/Math/clarke_forwardBlk.py, resources/blocks/rcpBlk/Math/clarke_inverseBlk.py, resources/blocks/rcpBlk/Math/park_forwardBlk.py, resources/blocks/rcpBlk/Math/park_inverseBlk.py
This commit adds new block for forward and inverse Clarke and Park transformations. Forward Clarke transformation can be used either with 2 or 3 inputs. The output values are averaging when using 3 inputs so the noise on channels has less effect on the control application.
=> Math: add blocks for Park and Clarke transformations

pysim-run.sh
Adds skript pysim-run.sh that allows to run pysimCoder without the application being installed on the system. PysimCoder can then
be run from its root directory by executing ./pysim-run.sh (on Linux systems).
=> add pysim-run.sh skript to run pysimCoder from source code without installation

CodeGen/nuttx/devices/serialOut.c, resources/blocks/blocks/NuttX/nuttxSerialOut.xblk, resources/blocks/rcpBlk/NuttX/nuttxSerialOutBlk.py
This change allows the user to select device port (ttyS0 etc.) from block parameters instead of having predefined one port in the code.
=> NuttX: update Serial Out block to select device port from parameters

BlockEditor/RTScope.py, BlockEditor/pyplt.ui
Small update for RTScope tool to allow selection of baud rate from the graphical widget instead of rewriting the code. Tested with sending data over UART from Teensy 4.1
=> RTScope: add option to select baud rate from the scope widget

CodeGen/Common/common_dev/discretePID.c
This fixes mistake in anti-windup computation in discrete PID block presented in PR #16. The wrong sign was causing instability in some cases.
=> Common: fix implementation of anti-windup in discrete PID block

CodeGen/LinuxRT/.gitignore, CodeGen/Raspberry_PI/.gitignore, CodeGen/SAMD21/.gitignore, CodeGen/STM32H7/.gitignore, CodeGen/linux_mz_apo/.gitignore
Added few gitignore files to ignore *.o and *.a files after compilation.
=> CodeGen: added .gitignore files to ignore *.o and *.a files

CodeGen/nuttx/devices/Makefile, CodeGen/templates/nuttx.tmf, CodeGen/templates/nuttx_sem.tmf
The pysimCoder models generation for NuttX target has been
tested only for ARM based targets till now.
RISC-V does not support -mlong-calls option which is used
on ARM targets to generate code which can be relocated
to call NuttX system exported symbols when model is build
as standalone application. Check for option availability
before its use.
Then ESP32C3 environment exported by NuttX specifies
multiple linker scripts which should be used. Be prepare
for more than one of them.
The last, nuttx-export/startup/esp32c3_head.o file
has to be included into whole NuttX image linking
command. It should be specified in Make.defs HEAD_OBJ.
It is missing there for now and Make.defs has to be tuned
manually.
Signed-off-by: Pavel Pisa <pisa@cmp.felk.cvut.cz>
=> CodeGen/nuttx: more makefiles tuning to support RISC-V (ESP32C3).

CodeGen/nuttx/devices/nuttx_PWM.c, resources/blocks/rcpBlk/NuttX/nuttx_PWMBlk.py
Change double params order from [umin, umax, freq] to [freq, umin, umax] so they are matched with corresponding xblk file. Wrong order results in parameters' names not being correctly matched.
The change does not affect block's functionality.
=> nuttxPWM: switch order of double parameters to match xblk file

CodeGen/linux_mz_apo/devices/Makefile, CodeGen/src/linux_main_rt.c, CodeGen/templates/rt_mz_apo.tmf
Hello Roberto,
Michal Lenc's SHV support propagated into MZ_APO template and libraries.
pysimCoder has been installed to our server supporting NFS read only loop to all
laboratories at our department. Generation tested to run on the MZ_APO
system
https://cw.fel.cvut.cz/wiki/_media/courses/b35apo/en/semestral/mz_apo-datasheet-en.pdf
with DC motor peripheral **dcsimpledrv**. Its VHDL sources are available there
https://gitlab.fel.cvut.cz/canbus/zynq/zynq-can-sja1000-top/-/tree/microzed-2dc/system/ip/dcsimpledrv_1.0
Best wishes,
Pavel
=> Mz apo shv

CodeGen/Raspberry_PI/devices/P3M_spi.c, CodeGen/Raspberry_PI/devices/rpi_gpclk.c, CodeGen/Raspberry_PI/devices/rpi_gpio.c, CodeGen/Raspberry_PI/devices/rpi_spimc.c, CodeGen/Raspberry_PI/include/rpi_gpclk.h, CodeGen/Raspberry_PI/include/rpi_gpio.h, CodeGen/Raspberry_PI/include/rpi_spimc.h, CodeGen/nuttx/devices/Makefile, CodeGen/nuttx/devices/nuttx_p3m_spi.c, CodeGen/nuttx/devices/pm_mc1_spi.c, CodeGen/nuttx/devices/pm_mc1_spi.h, resources/blocks/blocks/NuttX/P3MotorNuttx.xblk, resources/blocks/blocks/Raspberry/P3Motor.xblk, resources/blocks/rcpBlk/NuttX/P3MotNuttxBlk.py, resources/blocks/rcpBlk/Raspberry/P3MotBlk.py
These are all new blocks which are made for controlling a 3-Phase DC motor by utilizing an SPI connection with a hardware driver which uses FPGA.
One commit is only for the support given for NuttX, tested on the ESP32C3 RISC-V board.
The other commit is for support of RaspberryPi board for the same operations.
There is also one minor addition to the Makefile for the /nuttx/devices folder which includes more support files for the
"CONFIG_SPI=y" condition. 
Links to the documentation of previous implementation of the code on Simulink which was originally made
for the RaspberryPi can be seen here: 
https://gitlab.fel.cvut.cz/otrees/nuttx-demos/-/wikis/pmsm-control
The new code was developed for the purpose of making a Demonstration for my Bachelor's thesis. The .dgm files will be pushed to …
=> Blocks for control of 3-Phase DC motor over SPI

CodeGen/Common/common_dev/hall3ph2sec.c, CodeGen/Common/common_dev/pmsm_align.c, CodeGen/nuttx/devices/nuttxENC.c, resources/blocks/Icons/HALL_2_SEC.svg, resources/blocks/Icons/PMSM_Align.svg, resources/blocks/blocks/Math/hall3ph2sec.xblk, resources/blocks/blocks/Math/pmsm_align.xblk, resources/blocks/blocks/NuttX/nuttxENC.xblk, resources/blocks/rcpBlk/Math/hall3ph2secBlk.py, resources/blocks/rcpBlk/Math/pmsm_alignBlk.py, resources/blocks/rcpBlk/NuttX/nuttxENCBlk.py
This PR consists of three commits.
**Enhancement of NuttX Encoder block**
- added support for QEIOC_GETINDEX call (implemented to NuttX mainline in [8e2b4576](https://github.com/apache/incubator-nuttx/commit/8e2b4576bf422b3ef1be1f6a75068d3d974f117e), currently supported only with iMXRT MCU)
- QEIOC_GETINDEX returns encoder position, index position and index count with one IOCTL call
**Hall 2 Sectors block**
- This block converts 3 Hall signals to 6 sectors (3 bits)
**PMSM Align block**
- PMSM Align block computes the electric angle of PMSM. Based on the inputs (hall sector number, encoder position, index, index count) it determines whether the HALL sensors or encoder are used for the motor's angle. HALL sensors are used until the encoder hits its index.
=> Enhancement of NuttX Encoder block and addition of two blocks for PMSM control

CodeGen/Common/shv/include/shv_com.h, CodeGen/Common/shv/include/shv_tree.h, CodeGen/Common/shv/shv_com.c, CodeGen/Common/shv/shv_methods.c, CodeGen/Common/shv/shv_tree.c
The broker has been updated when we have discussed about
latest changes and as result of the broker update there
problem appeared. New broker version uses standard
map field within header metadata. This is according SHV
original design but simple C implementation was not
able to skip this kind of unused metadata in received
header parsing.
=> shv:  rewite ls to work without malloc and adapt for new broker

CodeGen/Common/posix/TCPdqf.h, CodeGen/Common/posix/TCPsocketAsync.c, resources/blocks/blocks/Communication/TCPsocketAsyncBlk.xblk, resources/blocks/rcpBlk/Communication/TCPsocketAsyncBlk.py
Current TCP block TCPsocketTXRX operates in the same thread as main application and thus can slow down the application and violate RT capabilities. It also waits for received data if RX is used.
While this behaviour may be required for some applications it is not ideal for others. This commit adds new block TCPsocketAsyncBlk that sends and receives data in separate threads. Configurable TX buffer is used to store data to be send.
=> Communication: add TCP block with asynchronous send and receive

BlockEditor/RTScope.py, CodeGen/src/linux_main_rt.c, CodeGen/src/nuttx_main.c
The TCP recv even in blocking mode is guaranteed only to wait for single byte. It can return with les bytes read than requested and if the data are delivered in packets not exactly aligned to the N * 8 bytes equivalent to configured number of signals then RT scope fails with message like
data = self.st.unpack(buf)
struct.error: unpack requires a buffer of 24 bytes
=> RT scope utility: ensure correct handling of TCP stream with unaligned chunks

CodeGen/Common/shv/include/shv_com.h, CodeGen/Common/shv/include/shv_methods.h, CodeGen/Common/shv/include/shv_pysim.h, CodeGen/Common/shv/include/shv_tree.h, CodeGen/Common/shv/shv_com.c, CodeGen/linux_mz_apo/devices/Makefile, CodeGen/templates/nuttx.tmf, CodeGen/templates/rt.tmf, CodeGen/templates/rt_mz_apo.tmf
Actual SHV has a different location of include files. This commit follows up previous fix commits but also changes the path in .c and .h files so it follows the current SHV include standard.
The change is done for both NuttX and LinuxRT targets
=> shv: fix compile error with incorrect include path

CodeGen/linux_mz_apo/devices/README.md, CodeGen/linux_mz_apo/devices/zynq_3pmdrv1.c, CodeGen/linux_mz_apo/devices/zynq_3pmdrv1_mc.c, CodeGen/linux_mz_apo/devices/zynq_3pmdrv1_mc.h, resources/blocks/blocks/linux_mz_apo/mz_apo_3pmdrv1.xblk, resources/blocks/rcpBlk/linux_mz_apo/mz_apo_3pmdrv1.py
Add mz_apo_3pmdrv1 block to control the PMSM motor.
Component VHDL design
https://gitlab.fel.cvut.cz/canbus/zynq/zynq-can-sja1000-top/-/tree/master/system/ip/pmsm_3pmdrv1_1.0?ref_type=heads
=> CodeGen/linux_mz_apo: Add PMSM control on MZ_APO board with 3pmdrv1 board

CodeGen/nuttx/devices/nuttx_PWM.c
Some attributes of the info could have been uninitialized.
Set all channels' polarity to active high (PWM_CPOL_HIGH).
=> CodeGen/nuttx/devices/nuttx_PWM.c: zeroed struct pwm_info_s info and define PWM polarity

CodeGen/nuttx/devices/nuttx_PWM.c
By this time, the dcpol attribute has been accepted into the NuttX mainline. This way, the default state of the PWM channel in the disabled state is the logical zero.
TODO: make this configurable in the GUI.
=> CodeGen/nuttx/devices/nuttx_PWM.c: init channels with PWM_DCPOL_LOW

toolbox/supsisim/supsisim/block.py
Construct a QtSvg.QSvgRenderer inside the method and calculate the bounds to render the SVG properly instead of rendering bitmaps.
This commit also imports QtSvg from PyQt5. It must be tested whether compatibility won't be broken.
=> toolbox/supsisim/supsisim/block.py: paint method renders SVG properly

CodeGen/templates/nuttx.tmf
EMBEDROMFS NuttX Makefile template option allows to embedded directory content into target application image in ROMFS. The content is mounted to /etc in the running NuttX system.
The content of the init.d/rcS file is executed by NSH at startup. It can be used to setup system or even load FPGA bitstream from other file stored under /etc, for example. The start of the pysimCoder model even with parameters is possible as the last action as well. It can be run even in background if "main &" is specified.
=> CodeGen/nuttx: optional ROMFS content can be mounted into /etc on target

CodeGen/Common/posix/TCPsocketAsync.c, CodeGen/Common/posix/TCPsocketTxRx.c, CodeGen/Common/posix/UDPsocketRx.c, CodeGen/Common/posix/UDPsocketTx.c, CodeGen/Common/posix/plotJuggler.c, CodeGen/Common/shv/shv_com.c
Without this header size of the structure is unknown on original BSD TCP/IP stack and code does not build for RTEMS which uses it.
=> Common: struct sockaddr_in is defined in netinet/in.h by standard

BlockEditor/pyplt.ui, BlockEditor/qtgRTScope.py
Reconfigure pyplt.ui to add a QTableWidget to incorporate names for signals. The number of rows depends on the number of signals in the Signals spin box. If the nth signal is empty, the name "Signal n" is used instead.
Please, look at the new QTForm. If you don't like anything I'd be happy to fix it.
=> BlockEditor/qtgRTScope.py: add support for pyqtgraph legends

CodeGen/Common/common_dev/discretePID.c
Change the sign in the I windup for another time. Antiwindup procedure should not depend on the sign of the saturation value. Refer to the diagram below.
=> CodeGen/Common/common_dev/discretePID.c: sign in I antiwindup

requirements.txt, toolbox/supsisim/supsisim/client.py
Pysimcoder no longer crashes with pyshv of latest version v0.6.1.
Pyshv v0.6.1 was also added to requirements.txt
=> fix: connected() funciton crashing on newver versions of pyshv

toolbox/supsisim/supsisim/editor.py
Item idents are calculated during code generation based on the connections between blocks. Newly introduced tuning over pySHV needs correct item idents even if the connection is made from a diagram without previous code generation. This fixes the issue when the diagram was reopened and tuning was not working.
=> toolbox/editor.py: use correct item idents in shvAction

CodeGen/nuttx/devices/nuttx_p3m_spi.c
Fix clearing the spimcst structure with memset and fix uint casting to first signed integer and then to double on the IRC position and offset for the 3 phase PMSM motor block for NuttX.
=> CodeGen/nuttx/devices/nuttx_p3m_spi.c: fix clearing spimcst structure and IRC parameters casting

CodeGen/Raspberry_PI/devices/P3M_spi.c, CodeGen/linux_mz_apo/devices/zynq_3pmdrv1.c
The correction is based on previous problems findings on NuttX PMSM interface.
=> CodeGen/linux_mz_apo and RPi: correct initialization of PMSM state and define IRC position as signed

CodeGen/templates/nuttx.tmf
Might be useful when a flashing script works with a binary file.
=> CodeGen/templates/nuttx.tmf: generate a raw binary executable

pysim-run.sh
Basically, this script acts as a launch wrapper around all .py files in BlockEditor because of the exported PYTHONPATH envvar.
=> pysim-run.sh: launches any app in BlockEditor

toolbox/supsisim/supsisim/shv/generator.py
RCPblk has no attribute real_par_names but rather realParNames.
Without this change, the code generation sometimes resulted in a runtime Python error.
=> toolbox/supsisim/supsisim/shv/generator.py: wrong variable names

CodeGen/nuttx/devices/Makefile, CodeGen/nuttx/devices/canopen.c, CodeGen/templates/nuttx.tmf, CodeGen/templates/nuttx_timehook.tmf, pysim-run.sh
- CodeGen/nuttx: more precise check if standalone ELF should be build
- Both templates, nuttx.tmf and nuttx_timehook.tmf, are updated including some more minor cleanups.
- CodeGen/nuttx: do not build SPI devices when CONFIG_SPI_EXCHANGE/SPIIOC_TRANSFER is missing
- CodeGen/nuttx: fix build when NuttX CAN supports extended ID
- When CONFIG_CAN_EXTID is set then extended ID flag should be filled (value defined) for sent messages even that there is  no support to define if ID is extended in sendMsg API.  The "extended" variable declaration has been missing.   It is now set to send all messages with standard ID.
- pysim-run.sh: fix/allow passing of path of a block diagram as the only parameter
- Some cleanup added as well. The find is called only if incorrect/unknown command is specified.
=> Nuttx: more robust detectection that standalone ELF is supported and some more cleanups

requirements.txt, toolbox/supsisim/supsisim/shv/client.py
`pyshv` version 0.8.0 has an incompatible change, `SimpleClient` is renamed to `SHVClient`. We still want to support older `pyshv` version because 0.8.0 requires Python 3.11 that might not be available in all distributions now.
This change allows to run pysimCoder and its SHV capabilities with both pyshv 0.8.0 and older versions.
Closes #106
=> supsisim/shv/client.py: support pyshv versions >=0.8.0

CodeGen/Common/shv/shv_com.c
This was potentially a source of disconnect reasons as the data was packed in a bad way.
This is only a temporary fix. The more stable implementation of the new silicon-heaven library is located here: https://github.com/silicon-heaven/shv-libs4c. The plan is to use this library in near future.
=> CodeGen/shv: increment rid in the send_ping function after the for loop
